name: kiipo_action_release_it
description: run release-it and push version bump to release and develop branches
inputs:
  github_token: 
    required: true
  repository_name:
    required: true
runs: 
  using: "composite"
  steps:
    - run: git config user.name "kiipobot"
      shell: bash
    - run: git config user.email "superuser@kiipo.com"
      shell: bash
    - run: git checkout release
      shell: bash
    - run: npm ci --ignore-scripts
      shell: bash
    - run: npm run lint
      shell: bash
    - run: npm run test
      shell: bash
    - run: npm run release:ci 
      shell: bash
    - run: git push https://kiipobot:${{ inputs.github_token }}@github.com/physioq/${{ inputs.repository_name }} release --force --follow-tags
      shell: bash
    - run: git checkout develop
      shell: bash
    - run: git fetch -v
      shell: bash
    - run: git merge origin/release
      shell: bash
    - run: git push https://kiipobot:${{ inputs.github_token }}@github.com/physioq/${{ inputs.repository_name }} develop --force --follow-tags
      shell: bash
