name: kiipo_action_release_it
description: run release-it and push version bump release branch
inputs:
  github_token: 
    required: true
  npm_token:
    required: true
runs: 
  using: "composite"
  steps:
    - run: git config user.name "kiipobot"
      shell: bash
    - run: git config user.email "superuser@kiipo.com"
      shell: bash
    - run: git checkout release
      shell: bash
    - run: npm ci --ignore-scripts
      shell: bash
      env: 
        KIIPO_BOT_NPM_AUTOMATION_TOKEN: ${{ inputs.npm_token }}
    - run: npm run lint
      shell: bash
    - run: npm run test
      shell: bash
    - run: npm run release:ci 
      shell: bash
      env: 
        KIIPO_BOT_NPM_AUTOMATION_TOKEN: ${{ inputs.npm_token }}
    - run: git push https://kiipobot:${{ inputs.github_token }}@github.com/${{ github.repository }} release --force --follow-tags
      shell: bash
